//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1026
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Data;
using Mono.Data.Sqlite;

namespace StridersVR.Domain
{
	public abstract class DbAccess
	{

		private String dbConnectionString = "URI=file:" + Application.dataPath + "/StridersVR_BD.sqlite";
		protected IDbConnection dbConnection;
		protected IDbCommand  dbCommand;
		protected IDataReader dbCmdReader;
		protected String sqlQuery = "";

		public void openConnection()
		{
			this.dbConnection = new SqliteConnection (this.dbConnectionString);
			this.dbConnection.Open ();
		}

		public void closeConnection()
		{
			this.dbConnection.Dispose ();
			this.dbConnection.Close ();
		}

	}
}

