//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1026
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using StridersVR.Domain;

namespace StridersVR.Modules.Menu.Data
{
	public class DbTraining : DbAccess
	{

		public DbTraining ()
		{
		}

		public List<Training> getTrainingList()
		{
			List<Training> _trainingList = new List<Training>();

			this.openConnection ();
			using (this.dbCommand = this.dbConnection.CreateCommand()) 
			{
				this.sqlQuery = "SELECT * FROM Training ORDER BY tr_name";
				this.dbCommand.CommandText = this.sqlQuery;
				using(this.dbCmdReader = this.dbCommand.ExecuteReader())
				{
					while(this.dbCmdReader.Read())
					{
						_trainingList.Add(new Training(this.dbCmdReader.GetString(1)));
					}
					return _trainingList;
				}
			}
		}

	}
}

