//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1026
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using StridersVR.Domain;

namespace StridersVR.Modules.Menu.Data
{
	public class DbUserLogin : DbAccess
	{

		private String username = "";

		public DbUserLogin (String username)
		{
			this.username = username;
		}


		public Boolean login()
		{
			this.openConnection ();
			using (this.dbCommand = this.dbConnection.CreateCommand()) 
			{
				this.sqlQuery = String.Format("SELECT * FROM User WHERE us_name=\'{0}\';",this.username.ToUpper());
				this.dbCommand.CommandText = this.sqlQuery;
				using(this.dbCmdReader = this.dbCommand.ExecuteReader())
				{
					if(this.dbCmdReader.Read())
					{
						this.closeConnection();
						return true;
					}
				}
				return this.createUser();
			}
		}

		private Boolean createUser()
		{
			try
			{
				this.sqlQuery = String.Format("INSERT INTO User(us_name) VALUES (\'{0}\');",this.username.ToUpper());
				this.dbCommand.CommandText = this.sqlQuery;
				this.dbCommand.ExecuteScalar();
				this.closeConnection();
				return true;
			}
			catch (Exception e)
			{
				Debug.LogException(e);
				return false;
			}
		}
	}
}

