//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1026
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using StridersVR.Domain;
using UnityEngine.UI;

namespace StridersVR.Modules.Menu.Logic
{
	public class ContextMenuCamera
	{

		private IStateMenu currentMenuState;
		private String actualUser = String.Empty;
		private List<Training> trainingList = null;
		private Training currentTraining = null;
		private Text uiTextTraining;

		public ContextMenuCamera (Text uiTextTraining)
		{
			this.uiTextTraining = uiTextTraining;
		}

		public Boolean startFeatures()
		{
			return this.currentMenuState.menuFeatures();
		}

		public void loginFailure(Text inGameText)
		{
			if (String.IsNullOrEmpty (this.actualUser)) 
			{
				inGameText.text = "Debe de identificarse primero.";
			} else 
			{
				inGameText.text = "¡Nombre inválido!";
			}
		}

		public void setNextTraining()
		{
			int _index = this.trainingList.IndexOf (this.currentTraining);
			int _maxIndex = this.trainingList.Count - 1;
			if (_index + 1 <= _maxIndex) 
			{
				this.setTraining (this.trainingList [_index + 1]);
			} else 
			{
				this.setTraining (this.trainingList [0]);
			}
		}

		public void setPreviousTraining()
		{
			int _index = this.trainingList.IndexOf (this.currentTraining);
			int _maxIndex = this.trainingList.Count - 1;
			if (_index - 1 >= 0) 
			{
				this.setTraining (this.trainingList [_index - 1]);
			} else 
			{
				this.setTraining (this.trainingList [_maxIndex]);
			}
		}


		#region Change states
		public void changeToLoginState()
		{
			this.currentMenuState = new StateMenuLogin (this);
		}

		public void changeToLogoutState()
		{
			this.currentMenuState = new StateMenuLogout (this);
		}

		public void changeToTrainingState()
		{
			this.currentMenuState = new StateMenuTraining (this);
		}

		public void changeToStatisticsState()
		{
			this.currentMenuState = new StateMenuStatistics ();
		}
		#endregion


		#region Properties
		public IStateMenu CurrentMenuState
		{
			get { return this.currentMenuState; }
			set { this.currentMenuState = value; }
		}
		
		public String ActualUser
		{
			get { return this.actualUser; }
			set { this.actualUser = value; }
		}

		public List<Training> TrainingList
		{
			get { return this.trainingList; }
			set { this.trainingList = value; }
		}

		public void setTraining(Training training)
		{
			this.currentTraining = training;
			this.uiTextTraining.text = training.Name;
		}

		public String getTrainingName
		{
			get { return this.currentTraining.Name; }
		}
		#endregion


	}
}

